# Generated by Django 3.1.3 on 2020-11-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('dics', models.CharField(max_length=200, verbose_name='Description')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
