# Generated by Django 3.1.3 on 2020-11-11 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Service Page Url'),
            preserve_default=False,
        ),
    ]
