# Generated by Django 3.1.3 on 2020-11-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('bx bxs-user', 'bx bxs-user'), ('bx bxs-time ', 'bx bxs-time'), ('bx bxs-book-open', 'bx bxs-book-open'), ('bx bxs-group', 'bx bxs-group'), ('bx bxs-business', 'bx bxs-business')], max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='services',
            name='link',
            field=models.URLField(blank=True, verbose_name='Service Page Url'),
        ),
    ]
