# Generated by Django 3.1.3 on 2020-11-11 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201111_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Service Page Url'),
        ),
    ]
