# Generated by Django 3.1.3 on 2020-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201111_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
