# Generated by Django 3.1.3 on 2020-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201111_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFollio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(max_length=10, verbose_name='Category')),
                ('title', models.CharField(max_length=10, verbose_name='Category')),
                ('img', models.ImageField(upload_to='port/')),
                ('link', models.URLField(blank=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.RenameField(
            model_name='industrial_trainging',
            old_name='project',
            new_name='company',
        ),
    ]
